### PR TITLE
feat: Impove the wait for postgres script

### PR DESCRIPTION
**Pull request by aria1991**
I made some modifications:

— Added a timeout variable and a start_time variable to keep track of the elapsed time. I also added an if statement that checks if the elapsed time has exceeded the timeout value. If it has, the script exits with an error message.

— Replaced the hardcoded database username and password with environment variables.

— Added the set -o pipefail command to ensure that the script fails if any command in a pipeline fails. I also added some error messages to make it easier to diagnose problems.

### CODE REVIEW

**Comment by cbaker6** [comment]
Thanks for the updates to the Postgres script! I’ll test these shortly.

Can you remove the codeql files? Those can end up producing many errors that will go unfixed as I don’t have a linter in this project

**Comment by aria1991** [comment]
> Thanks for the updates to the Postgres script! I’ll test these shortly.
> 
> Can you remove the codeql files? Those can end up producing many errors that will go unfixed as I don’t have a linter in this project

Hi @cbaker6. It's done!

**Comment by cbaker6** [comment]
I made some changes so this doesn't break the docker compose files

**Review by cbaker6 — APPROVED** [review]
LGTM! thanks for making your first contribution!

**Pull request merged**
